import re
from typing import Optional


GLOSSARY = {
    # ──────────────────────────────────────
    # 동료 캐릭터
    # ──────────────────────────────────────
    "Karlach": "카를라크",
    "Astarion": "아스타리온",
    "Gale": "게일",
    "Lae'zel": "레이젤",
    "Shadowheart": "섀도하트",
    "Wyll": "윌",
    "Jaheira": "자헤이라",
    "Minsc": "민스크",
    "Halsin": "할신",
    "Minthara": "민타라",
    "Nightsong": "밤의 노래",
    "Dark Urge": "어두운 충동",
    "Haunted One": "시달리는 자",
    "Viconia": "바이코니아",
    "Ketheric Thorm": "케더릭 토름",
    # ──────────────────────────────────────
    # 주요 NPC / 세력 / 신
    # ──────────────────────────────────────
    "Raphael": "라파엘",
    "Mizora": "미조라",
    "Orin": "오린",
    "Gortash": "고타쉬",
    "The Emperor": "황제",
    "Mind Flayer": "마인드 플레이어",
    "Illithid": "일리시드",
    "Absolute": "절대자",
    "The Absolute": "절대자",
    "Chosen": "선택받은 자",
    "Withers": "위더스",
    "Vlaakith": "블라키스",
    "Cazador": "카자도르",
    "Isobel": "이소벨",
    "Dame Aylin": "에일린 경",
    "Elminster": "엘민스터",
    # 신
    "Myrkul": "미어쿨",
    "Bhaal": "바알",
    "Bane": "베인",
    "Mystra": "미스트라",
    "Shar": "샤",
    "Selune": "셀루네",
    "Lathander": "라샌더",
    "Lolth": "롤쓰",
    "Tyr": "티르",
    "Silvanus": "실바누스",
    "Tempus": "템퍼스",
    # 세력
    "Flaming Fist": "불주먹 용병대",
    "Zhentarim": "젠타림",
    "Harpers": "하퍼",
    "Emerald Grove": "에메랄드 숲",
    "Goblin": "고블린",
    "Githyanki": "기스양키",
    "Cambion": "캠비온",
    "Nautiloid": "노틸로이드",
    "Underdark": "언더다크",
    "Sword Coast": "소드 코스트",
    "Faerun": "페이룬",
    "Astral Plane": "아스트랄계",
    "Nine Hells": "나인 헬",
    # ──────────────────────────────────────
    # 종족
    # ──────────────────────────────────────
    "Human": "인간",
    "Elf": "엘프",
    "High Elf": "하이 엘프",
    "Wood Elf": "우드 엘프",
    "Drow": "드로우",
    "Lolth-Sworn Drow": "롤쓰 스원 드로우",
    "Seldarine Drow": "셀다린 드로우",
    "Tiefling": "티플링",
    "Asmodeus Tiefling": "아스모데우스 티플링",
    "Mephistopheles Tiefling": "메피스토펠레스 티플링",
    "Zariel Tiefling": "자리엘 티플링",
    "Dwarf": "드워프",
    "Gold Dwarf": "골드 드워프",
    "Shield Dwarf": "실드 드워프",
    "Duergar": "드웨가",
    "Halfling": "하플링",
    "Lightfoot Halfling": "라이트풋 하플링",
    "Strongheart Halfling": "스트롱하트 하플링",
    "Gnome": "노움",
    "Rock Gnome": "바위 노움",
    "Forest Gnome": "숲 노움",
    "Deep Gnome": "딥 노움",
    "Half-Elf": "하프엘프",
    "High Half-Elf": "하이 하프 엘프",
    "Wood Half-Elf": "우드 하프 엘프",
    "Drow Half-Elf": "드로우 하프 엘프",
    "Dragonborn": "드래곤본",
    "Half-Orc": "하프오크",
    # ──────────────────────────────────────
    # 능력치 (6대 스탯)
    # ──────────────────────────────────────
    "Strength": "근력",
    "Dexterity": "민첩",
    "Constitution": "건강",
    "Intelligence": "지능",
    "Wisdom": "지혜",
    "Charisma": "매력",
    # ──────────────────────────────────────
    # 직업
    # ──────────────────────────────────────
    "Barbarian": "바바리안",
    "Wildheart": "야생의심장",
    "Berserker": "광전사",
    "Wild Magic": "야생 마법",
    "Giant": "거인",
    "Bard": "바드",
    "College of Lore": "전승학파",
    "College of Valour": "용맹학파",
    "College of Swords": "검술학파",
    "College of Glamour": "요술학파",
    "Cleric": "클레릭",
    "Life Domain": "생명 권역",
    "Light Domain": "빛 권역",
    "Trickery Domain": "기만 권역",
    "Knowledge Domain": "지식 권역",
    "Nature Domain": "자연 권역",
    "Tempest Domain": "폭풍 권역",
    "War Domain": "전쟁 권역",
    "Death Domain": "죽음 권역",
    "Druid": "드루이드",
    "Circle of the Land": "땅의 회합",
    "Circle of the Moon": "달의 회합",
    "Circle of the Spores": "포자의 회합",
    "Circle of the Stars": "별의 회합",
    "Fighter": "파이터",
    "Battle Master": "전투의 대가",
    "Eldritch Knight": "비술 기사",
    "Champion": "투사",
    "Arcane Archer": "비전 궁수",
    "Monk": "몽크",
    "Way of the Four Elements": "사원소의 길",
    "Way of the Open Hand": "열린 손의 길",
    "Way of Shadow": "그림자의 길",
    "Way of the Drunken Master": "취권 달인의 길",
    "Paladin": "팔라딘",
    "Oath of Devotion": "헌신의 맹세",
    "Oath of the Ancients": "선조의 맹세",
    "Oath of Vengeance": "복수의 맹세",
    "Oath of the Crown": "왕관의 맹세",
    "Oathbreaker": "맹세파기자",
    "Ranger": "레인저",
    "Hunter": "사냥꾼",
    "Beast Master": "야수 조련사",
    "Gloom Stalker": "어둠 추척자",
    "Swarmkeeper": "무리지기",
    "Rogue": "로그",
    "Thief": "도둑",
    "Arcane Trickster": "비전 괴도",
    "Assassin": "암살자",
    "Swashbuckler": "칼잡이",
    "Sorcerer": "소서러",
    "Draconic Bloodline": "용의 혈통",
    "Storm Sorcery": "폭풍 술사",
    "Shadow Magic": "그림자 마법",
    "Warlock": "워락",
    "The Fiend": "마족",
    "The Great Old One": "고대의 지배자",
    "The Archfey": "대요정",
    "The Hexblade": "주술 칼날",
    "Hexblade": "주술 칼날",
    "Pact of the Chain": "사슬의 계약",
    "Pact of the Blade": "검의 계약",
    "Pact of the Tome": "장서의 계약",
    "Wizard": "위저드",
    "Bladesinging": "칼날 노래",
    "Bladesinger": "칼날 노래",
    # ──────────────────────────────────────
    # 주문 학파 (긴 표현 먼저 - 부분 매칭 방지)
    # ──────────────────────────────────────
    "School of Abjuration": "방호술",
    "Abjuration School": "방호술",
    "Abjuration": "방호술",
    "School of Evocation": "방출술",
    "Evocation School": "방출술",
    "Evocation": "방출술",
    "School of Necromancy": "사령술",
    "Necromancy School": "사령술",
    "Necromancy": "사령술",
    "School of Conjuration": "창조술",
    "Conjuration School": "창조술",
    "Conjuration": "창조술",
    "School of Enchantment": "환혹술",
    "Enchantment School": "환혹술",
    "Enchantment": "환혹술",
    "School of Divination": "예지술",
    "Divination School": "예지술",
    "Divination": "예지술",
    "School of Illusion": "환영술",
    "Illusion School": "환영술",
    "Illusion": "환영술",
    "School of Transmutation": "변환술",
    "Transmutation School": "변환술",
    "Transmutation": "변환술",
    # ──────────────────────────────────────
    # 주문명
    # ──────────────────────────────────────
    "Fireball": "화염구",
    "Lightning Bolt": "번개 줄기",
    "Haste": "가속",
    "Slow": "둔화",
    "Invisibility": "투명화",
    "Greater Invisibility": "상위 투명화",
    "Misty Step": "안개 걸음",
    "Thunderwave": "천둥파",
    "Animate Dead": "망자 조종",
    "Speak with Dead": "망자와 대화",
    "Polymorph": "변신",
    "Counterspell": "주문 방해",
    "Bless": "축복",
    "Hex": "주술",
    "Healing Word": "치유의 단어",
    "Cure Wounds": "상처 치유",
    "Revivify": "생환",
    "Shield of Faith": "신념의 보호막",
    "Spirit Guardians": "영혼의 수호자",
    "Eldritch Blast": "섬뜩한 작렬",
    "Magic Missile": "마법의 화살",
    "Mage Hand": "마법사의 손",
    "Sacred Flame": "신성한 불꽃",
    "Guidance": "인도",
    "Darkness": "어둠",
    "Daylight": "일광",
    "Dispel Magic": "마법 해제",
    "Hold Person": "인물 속박",
    "Hold Monster": "괴물 속박",
    "Dimension Door": "차원문",
    "Fly": "비행",
    "Feather Fall": "깃털 낙하",
    "Knock": "개방",
    "Pass Without Trace": "흔적 없는 이동",
    "Silence": "침묵",
    "Smite": "강타",
    "Divine Smite": "신성 강타",
    "Sneak Attack": "급소 공격",
    "Wild Shape": "야생 변신",
    "Rage": "격노",
    "Action Surge": "행동 쇄도",
    "Second Wind": "재기",
    "Lay on Hands": "레이온핸즈",
    "Bardic Inspiration": "바드의 영감",
    "Channel Divinity": "신성한 도관",
    "Ki": "기",
    "Sorcery Points": "소서리 점수",
    "Metamagic": "초마법",
    # ──────────────────────────────────────
    # 전투 / 시스템 용어
    # ──────────────────────────────────────
    "Attack Rolls": "공격 굴림",
    "Attack Roll": "공격 굴림",
    "attack rolls": "공격 굴림",
    "attack roll": "공격 굴림",
    "Saving Throws": "내성 굴림",
    "Saving Throw": "내성 굴림",
    "saving throws": "내성 굴림",
    "saving throw": "내성 굴림",
    "Damage Roll": "피해 굴림",
    "Damage Rolls": "피해 굴림",
    "Ability Check": "능력 판정",
    "Ability Checks": "능력 판정",
    "Armor Class": "방어도",
    "Armour Class": "방어도",
    "Hit Points": "체력",
    "Hit Dice": "생명력 주사위",
    "Proficiency": "숙련",
    "Proficiency Bonus": "숙련 보너스",
    "Expertise": "통달",
    "Advantage": "유리",
    "Disadvantage": "불리",
    "Concentration": "집중",
    "Bonus Action": "추가 행동",
    "Bonus Actions": "추가 행동",
    "Reaction": "반응",
    "Reactions": "반응",
    "Critical Hit": "치명타",
    "Critical Hits": "치명타",
    "Inspiration": "영감",
    "Initiative": "선제권",
    "Spell Slot": "주문 슬롯",
    "Spell Slots": "주문 슬롯",
    "Spell Save DC": "주문 내성 난이도",
    "Difficulty Class": "난이도",
    "Cantrip": "소마법",
    "Cantrips": "소마법",
    "Ritual": "의식",
    "Short Rest": "짧은 휴식",
    "Long Rest": "긴 휴식",
    "Camp": "야영지",
    "Multiclassing": "멀티 클래싱",
    "Finesse": "기교",
    "Versatile": "다용도",
    "Two-Handed": "양손",
    "Light Armor": "경갑",
    "Medium Armor": "평갑",
    "Heavy Armor": "중갑",
    "Shield": "방패",
    "Feat": "재주",
    "Feats": "재주",
    "Background": "배경",
    # ──────────────────────────────────────
    # 상태이상 / 상태 효과
    # ──────────────────────────────────────
    "Prone": "쓰러짐",
    "Stunned": "기절",
    "Frightened": "공포",
    "Charmed": "매혹",
    "Poisoned": "중독",
    "Blinded": "실명",
    "Deafened": "귀먹음",
    "Restrained": "속박",
    "Paralyzed": "마비",
    "Petrified": "석화",
    "Incapacitated": "행동불능",
    "Invisible": "투명",
    "Exhaustion": "피로",
    "Burning": "불타는",
    "Bleeding": "출혈",
    "Blessed": "축복받은",
    "Cursed": "저주받은",
    "Sleeping": "수면",
    "Entangled": "얽힘",
    # ──────────────────────────────────────
    # 피해 유형
    # ──────────────────────────────────────
    "Fire Damage": "화염 피해",
    "Cold Damage": "냉기 피해",
    "Lightning Damage": "번개 피해",
    "Thunder Damage": "천둥 피해",
    "Radiant Damage": "광휘 피해",
    "Necrotic Damage": "괴저 피해",
    "Psychic Damage": "정신 피해",
    "Poison Damage": "독 피해",
    "Acid Damage": "산 피해",
    "Force Damage": "역장 피해",
    "Bludgeoning Damage": "타격 피해",
    "Piercing Damage": "관통 피해",
    "Slashing Damage": "참격 피해",
    "Healing": "치유",
    "Temporary Hit Points": "임시 체력",
    "Radiant": "광휘",
    "Necrotic": "괴저",
    "Psychic": "정신",
    "Bludgeoning": "타격",
    "Piercing": "관통",
    "Slashing": "참격",
    # ──────────────────────────────────────
    # 기술 (Skills)
    # ──────────────────────────────────────
    "Acrobatics": "곡예",
    "Animal Handling": "동물 조련",
    "Arcana": "비전학",
    "Athletics": "운동",
    "Deception": "기만",
    "History": "역사",
    "Insight": "통찰",
    "Intimidation": "위협",
    "Investigation": "수사",
    "Medicine": "의학",
    "Nature": "자연",
    "Perception": "인지",
    "Performance": "연행",
    "Persuasion": "설득",
    "Religion": "종교",
    "Sleight of Hand": "손재주",
    "Stealth": "은신",
    "Survival": "생존",
    # ──────────────────────────────────────
    # 기타 게임 용어
    # ──────────────────────────────────────
    "Darkvision": "암시야",
    "Superior Darkvision": "상위 암시야",
    "Resistance": "저항",
    "Immunity": "면역",
    "Vulnerability": "취약",
    "Familiar": "패밀리어",
    "Companion": "동료",
    "Tadpole": "올챙이",
    "Ceremorphosis": "세레모포시스",
    "Elder Brain": "엘더 브레인",
    "Psionic": "사이오닉",
}


def try_glossary_only(text: str) -> Optional[str]:
    stripped = text.strip()
    if stripped in GLOSSARY:
        return GLOSSARY[stripped]
    for src, dst in GLOSSARY.items():
        if stripped.lower() == src.lower():
            return dst
    return None


def build_glossary_prompt_section() -> str:
    if not GLOSSARY:
        return ""
    lines = ["[고유 용어 번역 규칙]",
             "아래 용어는 원문에 등장할 경우 반드시 지정된 한국어로 번역한다."]
    for src, dst in GLOSSARY.items():
        lines.append(f"  {src} -> {dst}")
    lines.append("")
    return "\n".join(lines) + "\n"


def apply_glossary(text: str) -> str:
    if not GLOSSARY:
        return text
    for src, dst in sorted(GLOSSARY.items(), key=lambda x: len(x[0]), reverse=True):
        text = re.sub(r'\b' + re.escape(src) + r'\b', dst, text)
    return text
